route:
    repeat_interval: 30m
    group_interval: 30m
    receiver: 'monitoramento-stack'

receivers:
    - name: 'monitoramento-stack'
      webhook_configs:
          - send_resolved: false
            url: 'INCOMING_WEBHOOK'
