global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'Stack-Monitoring'
rule_files:
  - "alert.rules"
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
      
  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'tcp-socat'
    dns_sd_configs:
    - names:
      - 'tasks.tcp-socat'
      type: 'A'
      port: 2375
#  - job_name: 'server-master'
#    metrics_path: '/api/v1/allmetrics'
#    params:
#      format: [prometheus]
#    honor_labels: true
#    scrape_interval: 5s
#    static_configs:
#         - targets: ['192.168.10.103:19999']

  - job_name: 'nginx-exporter'
    metrics_path: '/metrics'
    params:
      format: [prometheus]
    scrape_interval: 2s
    scrape_timeout: 1s
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'php-fpm-exporter'
    metrics_path: '/metrics'
    params:
      format: [prometheus]
    scrape_interval: 2s
    scrape_timeout: 1s
    static_configs:
      - targets: ['php-fpm-exporter:9253']

  - job_name: consul
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,dev,.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job      